(source gnu)
(source melpa)

(depends-on "company")

(depends-on "flycheck")

(depends-on "rust-mode")
(depends-on "racer")
(depends-on "company-racer")
(depends-on "flycheck-rust")
(depends-on "rustfmt")

(depends-on "toml-mode")
