(source gnu)
(source melpa)

(depends-on "monokai-theme")

(depends-on "company")

(depends-on "flycheck")
(depends-on "flycheck-pos-tip")

(depends-on "rust-mode")
(depends-on "racer")
(depends-on "company-racer")
(depends-on "flycheck-rust")
(depends-on "flycheck-cargo")
(depends-on "rustfmt")

(depends-on "toml-mode")
