(source gnu)
(source melpa)

; cannot find undo-tree package...
; (depends-on "undo-tree")

(depends-on "monokai-theme")

(depends-on "company")
(depends-on "company-racer")

(depends-on "flycheck")
(depends-on "flycheck-pos-tip")

(depends-on "toml-mode")

(depends-on "markdown-mode")
(depends-on "json-mode")
(depends-on "yaml-mode")
