(source gnu)
(source melpa)

(depends-on "monokai-theme")

(depends-on "company")

(depends-on "flycheck")
(depends-on "flycheck-pos-tip")

(depends-on "rust-mode")
(depends-on "cargo")
(depends-on "racer")
(depends-on "company-racer")
(depends-on "flycheck-rust")
(depends-on "rustfmt")

(depends-on "markdown-mode")
(depends-on "json-mode")
(depends-on "yaml-mode")
(depends-on "toml-mode")

(depends-on "thrift-mode")

(depends-on "scala-mode2")
