(global-set-key [C-up] 'shrink-frame-height)
(global-set-key [C-down] 'expand-frame-height)
(global-set-key [C-left] 'shrink-frame-width)
(global-set-key [C-right] 'expand-frame-width)
(global-set-key "\C-c\C-r" 'recentf-open-files)
(global-set-key "\C-h" 'delete-backward-char)
(global-set-key "\C-xr" 're-builder)
(global-set-key "\C-x\C-r" 'query-replace-regexp)
(global-set-key "\C-x?" 'help-command)
(global-set-key "\C-x\C-n" 'other-window)
(global-set-key "\C-x\C-p" 'other-window-backward)
(global-set-key "\C-xg" 'goto-line)
(global-set-key "\C-x\C-g" 'grep)
(global-set-key "\C-xw" 'wrap-region-by-string)
(global-set-key "\C-\\" 'redo)
(global-set-key "\C-c\C-i" 'fold-dwim-toggle)
(global-set-key "\M-a" 'align-regexp)
(global-set-key "\M-h" 'backward-kill-word)

;; etags
(global-set-key "\M-s" 'tags-search)  ; M-, to next candidate
