(global-set-key "\C-c\C-r" 'recentf-open-files)
(global-set-key "\C-h" 'delete-backward-char)
(global-set-key "\C-xr" 're-builder)
(global-set-key "\C-x\C-r" 'query-replace-regexp)
(global-set-key "\C-x?" 'help-command)
(global-set-key "\C-x\C-n" 'other-window)
(global-set-key "\C-x\C-p" 'other-window-backward)
(global-set-key "\C-xg" 'goto-line)
(global-set-key "\C-x\C-g" 'grep)
(global-set-key "\C-\\" 'redo)
(global-set-key "\M-h" 'backward-kill-word)

(global-set-key "\M-n" 'flycheck-next-error)
(global-set-key "\M-p" 'flycheck-previous-error)
