brew install autoconf
brew install awscli
brew install bash
brew install cask
brew install emacs
brew install flyway
brew install git
brew install gnu-sed
brew install libevent
brew install libssh2
brew install mysql
brew install openssl
brew install peco
brew install pkg-config
brew install pyenv
brew install readline
brew install reattach-to-user-namespace
brew install rust
brew install sbt
brew install tmux
brew install wget
